### ISSUE TITLE
DUAL XEON E5-2680 v3 • System is unresponsive and laggy • Audio playback is crackling

### ISSUE THREAD

**Issue by analogo** [Piker-Alpha/ssdtPRGen.sh#179]
Dear Pike..

I wrote you following message..
https://pikeralpha.wordpress.com/2015/12/29/skylake-bus-speed-tip/comment-page-1/#comment-4879

---

_Hello pikeralpha .._

_For many weeks I´m trying almost continuously to solve a big problem and you are maybe my last hope, because you have very deep knowledge .._

_My system works, but extremely unresponsive and sluggish with nvda_drv=1, so that it is unusable. For example, the entire system works unresponsive and hangs / lags frequently up to 30 seconds, if I use a program, so that only the mouse can be moved._

_Also, my two major DAW programs Ableton Live and Bitwig Studio, which are very important for me, have big problems with audio playback and does not seem to cope with the CPUs._

_With nv_disable=1, the system works almost smoothly, but the audio playback still is full of crackling._

_On your website, I found a comment from someone who had the same problem on a DUAL XEON system. There I found that from you:_

_ioreg -rp IODeviceTree -c IOACPIPlatformDevice -k cpu-type|grep cpu-type_

_I got 192 times (!!) “CPU type” = . Actually, it should be 32 for 2x 8-core..(?)_

_If you need more details, please look here:_

_http://www.insanelymac.com/forum/topic/309899-asus-z10pe-d8-ws-•-2x-xeon-e5-2680-v3-•-clover-•-el-capitan-•-system-lags-freezes/_

_http://www.tonymacx86.com/el-capitan-desktop-support/180510-asus-z10pe-d8-ws-2x-xeon-2680v3-clover-el-capitan-system-lags-hangs.html_

_Also I gladly can mail anything whatever you need to get the issue on the track, like ioreg files, log files, DSDT / SSDT, etc._

_Please help me, because I no longer know what to try.._

_Many Thanks to Spain! :)_

_My system:_

_– Asus Z10PE-D8 WS
– DUAL XEON E5-2680 v3
– 8x 4GB RDIMMs
– MSI GTX 960 Gaming 4G
– OS X 10.11.2
– Clover_

_– CPU BIOS setting: 2x 8-core instead of 2x 12-core_

---

First many Thanks for your answer! ;)

Today I tried again some seetings with ssdtPRGen.sh, but it´s always the same..

With nvda_drv=1 the system is working unresponsive and laggy like hell (unusable) and with nv_disable=1 almost smoothly, but a little bit flickering, because the Nvidia drivers are not loaded.

Most important for me is, that the audio playback of Ableton Live and Bitwig Studio is crackling-free, but always (with nvda_drv=1 and nv_disable=1) the audio playback is full of crackling. :(((

Immediately I will mail all files you are needing to analyze the problem to your e-Mail address which is shown in ssdtPRGen.sh.

Please look your e-Mail account and let me know, if you need more information..

My ssdtPRGen.sh Settings:
./ssdtPRGen.sh -b Mac-27ADBB7B4CEE8E61 -p 'E5-2680 v3' -c 2 -l 16 -x 1 -w 1

In both ioreg files I did following in OS X:
- Opened Cinebench, ran a CPU benchmark and closed the program.
- Opened Ableton Live (you can filter with "live"), tested the audio playback and closed the program.
- Opened IORegistryExplorer v2.1, saved the configuration and closed the program.

In the System nvda_drv=1.ioreg file you will find extreme lags.. (filter with "second" or "unresponsive")

Many Thanks, my best wishes to you and a happy new year in a few hours! ;)

**Comment by Piker-Alpha** [comment]
Are the Processor declarations defined in your DSDT or in one of the SSDT's?

And just for the record. We are talking about this processor:
http://ark.intel.com/products/81908/Intel-Xeon-Processor-E5-2680-v3-30M-Cache-2_50-GHz
Correct? If yes, then you have a total of 24 cores and 48 threads, but since you are using 16 core (limited by BIOS setting) you should be using -l 32 (with hyper-threading).

You may e-mail me your IORegistryExplorer dump (use version 2.1).

**Comment by analogo** [comment]
Thanks for your answer! :)

Correct, on the mainboard are two E5-2680 v3 installed. I mailed you twelve days ago a ZIP with ioreg, DSDT, SSDT, Console logfile, etc. Did you get the eMail? Otherwise I will mail again..

**Comment by Piker-Alpha** [comment]
Ok. Thanks. Will have another look (I am getting over 500 e-mails per week). 

Edit: Got it, but you forgot to add the DSDT.aml (see ~/Library/ssdtPRGen/DSDT.aml).

**Comment by analogo** [comment]
OMG.. :D  Have sent the eMail 31th december 2015..

**Comment by analogo** [comment]
Please look for the DSDT.aml in ZIP file (folder: "Files not used" ...)

**Comment by analogo** [comment]
With ./ssdtPRGen.sh -m MacPro6,1 -c 2 -d 3 -l 24 -x 1 -w 1 (all 24 cores enabled / HT disabled) I got 35 errors:

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen

##              v16.5 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

Override value: (-m) model, now using: MacPro6,1!
Override value: (-c) CPU type, now using: Haswell!
Override value: (-d) debug mode, now using: 3!
Override value: (-l) number of logical processors, now using: 24!
Override value: (-x) XCPM mode, now set to: 1!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!

System information: Mac OS X 10.11.2 (15C50)
Brandstring 'Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz'

gModelDataVersion: 160
Checking Sandy Bridge processor data ...
Checking Ivy Bridge processor data ...
Checking Haswell processor data ...
Processor data found for the Intel E5-2680 v3
Downloading extractACPITables.zip ...Unzipping extractACPITables.zip ...Checking executing bit of extractACPITables ...Cleanups ...Extracting ACPI tables ... Done.
4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b82471f53434b30085f4849440d414350493030303400
5b82471f53434b31085f4849440d414350493030303400
5b82471f53434b32085f4849440d414350493030303400
5b82471f53434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK0) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
logicalCore: 1 CP01
logicalCore: 2 CP02
logicalCore: 3 CP03
logicalCore: 4 CP04
logicalCore: 5 CP05
logicalCore: 6 CP06
logicalCore: 7 CP07
logicalCore: 8 CP08
logicalCore: 9 CP09
logicalCore: 10 CP0A
logicalCore: 11 CP0B
logicalCore: 12 CP00
logicalCore: 13 CP01
logicalCore: 14 CP02
logicalCore: 15 CP03
logicalCore: 16 CP04
logicalCore: 17 CP05
logicalCore: 18 CP06
logicalCore: 19 CP07
logicalCore: 20 CP08
logicalCore: 21 CP09
logicalCore: 22 CP0A
logicalCore: 23 CP0B
Extracting ACPI tables ... Done.
Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core E5-2680 v3 processor [0x306F2] setup [0x0507]
Processor matched!
With a maximum TDP of 120 Watt, as specified by Intel
Number logical CPU's: 24 (Core Frequency: 2500 MHz)
Number of Turbo States: 8 (2600-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Downloading iasl.zip ...Unzipping iasl.zip ...Setting executing bit of iasl ...Cleanups ...Done.
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ACPI Warning: NsLookup: Type mismatch on APSS (Package), searching for (Method) (20140926/nsaccess-729)
/Users/lars/Library/ssdtPRGen/ssdt.dsl     32:     External (_SB_.SCK0.CP00, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP00)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     33:     External (_SB_.SCK0.CP01, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP01)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     34:     External (_SB_.SCK0.CP02, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP02)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     35:     External (_SB_.SCK0.CP03, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP03)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     36:     External (_SB_.SCK0.CP04, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP04)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     37:     External (_SB_.SCK0.CP05, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP05)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     38:     External (_SB_.SCK0.CP06, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP06)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     39:     External (_SB_.SCK0.CP07, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP07)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     40:     External (_SB_.SCK0.CP08, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP08)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     41:     External (_SB_.SCK0.CP09, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP09)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     42:     External (_SB_.SCK0.CP0A, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP0A)

/Users/lars/Library/ssdtPRGen/ssdt.dsl     43:     External (_SB_.SCK0.CP0B, DeviceObj)
Error    6074 -                                          Name already exists in scope ^  (_SB_.SCK0.CP0B)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    365:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    377:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    384:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    384:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Remark   2098 -                                                                              Recursive method call ^  (_SB_.SCK0.CP01.ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    389:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    396:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    401:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    408:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    413:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    420:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    425:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    432:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    437:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    444:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    449:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    456:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    461:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    468:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    473:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    480:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    485:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    492:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    497:         Method (APSS, 0, NotSerialized)
Error    6074 -                     Name already exists in scope ^  (APSS)

/Users/lars/Library/ssdtPRGen/ssdt.dsl    504:         Method (ACST, 0, NotSerialized) { Return (_SB_.SCK0.CP01.ACST ()) }
Error    6074 -                     Name already exists in scope ^  (ACST)

ASL Input:     /Users/lars/Library/ssdtPRGen/ssdt.dsl - 508 lines, 14098 bytes, 167 keywords

Compilation complete. 35 Errors, 0 Warnings, 1 Remarks, 0 Optimizations

---

Maybe because ssdtPRGen generates only values for Device (SCK0) and not Device (SCK1)? 

DSDT.aml:

```
        Device (SCK0)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK0")
            Processor (CP00, 0x00, 0x00000410, 0x06) {}
            Processor (CP01, 0x02, 0x00000410, 0x06) {}
            Processor (CP02, 0x04, 0x00000410, 0x06) {}
            Processor (CP03, 0x06, 0x00000410, 0x06) {}
            Processor (CP04, 0x08, 0x00000410, 0x06) {}
            Processor (CP05, 0x0A, 0x00000410, 0x06) {}
            Processor (CP06, 0x10, 0x00000410, 0x06) {}
            Processor (CP07, 0x12, 0x00000410, 0x06) {}
            Processor (CP08, 0x14, 0x00000410, 0x06) {}
            Processor (CP09, 0x16, 0x00000410, 0x06) {}
            Processor (CP0A, 0x18, 0x00000410, 0x06) {}
            Processor (CP0B, 0x1A, 0x00000410, 0x06) {}
            Processor (CP0C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP10, 0xFF, 0x00000410, 0x06) {}
            Processor (CP11, 0xFF, 0x00000410, 0x06) {}
            Processor (CP12, 0xFF, 0x00000410, 0x06) {}
            Processor (CP13, 0xFF, 0x00000410, 0x06) {}
            Processor (CP14, 0xFF, 0x00000410, 0x06) {}
            Processor (CP15, 0xFF, 0x00000410, 0x06) {}
            Processor (CP16, 0xFF, 0x00000410, 0x06) {}
            Processor (CP17, 0xFF, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }

        Device (SCK1)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK1")
            Processor (CP00, 0x20, 0x00000410, 0x06) {}
            Processor (CP01, 0x22, 0x00000410, 0x06) {}
            Processor (CP02, 0x24, 0x00000410, 0x06) {}
            Processor (CP03, 0x26, 0x00000410, 0x06) {}
            Processor (CP04, 0x28, 0x00000410, 0x06) {}
            Processor (CP05, 0x2A, 0x00000410, 0x06) {}
            Processor (CP06, 0x30, 0x00000410, 0x06) {}
            Processor (CP07, 0x32, 0x00000410, 0x06) {}
            Processor (CP08, 0x34, 0x00000410, 0x06) {}
            Processor (CP09, 0x36, 0x00000410, 0x06) {}
            Processor (CP0A, 0x38, 0x00000410, 0x06) {}
            Processor (CP0B, 0x3A, 0x00000410, 0x06) {}
            Processor (CP0C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP10, 0xFF, 0x00000410, 0x06) {}
            Processor (CP11, 0xFF, 0x00000410, 0x06) {}
            Processor (CP12, 0xFF, 0x00000410, 0x06) {}
            Processor (CP13, 0xFF, 0x00000410, 0x06) {}
            Processor (CP14, 0xFF, 0x00000410, 0x06) {}
            Processor (CP15, 0xFF, 0x00000410, 0x06) {}
            Processor (CP16, 0xFF, 0x00000410, 0x06) {}
            Processor (CP17, 0xFF, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }
```

**Comment by Piker-Alpha** [comment]
The main problem is the duplicated processor declarations (CPNN is used twice) and that was not supported by the script. Hopefully v17.0 takes care of it. Note that I changed one argument and added a new one:

OLD: ./ssdtPRGen.sh -b Mac-27ADBB7B4CEE8E61 -p 'E5-2680 v3' -c 2 -l 32 -x 1 -w 1

NEW: ./ssdtPRGen.sh -b Mac-27ADBB7B4CEE8E61 -p 'E5-2680 v3' -target 2 -l 32 -x 1 -w 1 -cpus 2

p.s. You should not need: the -p argument. Possibly also not the -b argument.

**Comment by analogo** [comment]
Thank you!

I don´t use the -p argument anymore (please look my last post). Can I already use the new -cpus parameter or can I edit manually the SSDT?

Did you look the files (Console logfile, IOREG, etc.)? Do you have an idea, why the Dual Xeon system is working so laggy and unresponsive?

Edit:

I saw your edit of ssdtPRGen.sh and will try in a few minutes.. :)

**Comment by analogo** [comment]
I got following error with -cpus (tried also with -c, but the same):

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen

##              v17.0 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

Error: Invalid argument detected: —cpus (check ssdtPRGen.sh -h)
Aborting ...
Done.

---

Tried following:

./ssdtPRGen.sh -cpus 2 -target 2 -d 3 -l 24 -x 1 -w 1
./ssdtPRGen.sh -c 2 -target 2 -d 3 -l 24 -x 1 -w 1

**Comment by analogo** [comment]
Adding -l is the problem..

With "./ssdtPRGen.sh -cpus 2 -target 2 -d 3 -x 1 -w 1" I got following:

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen

##              v17.0 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

Override value: (-cpus) number of processors, now using: 2!
Override value: (-target) CPU, now using: Haswell!
Override value: (-d) debug mode, now using: 3!
Override value: (-x) XCPM mode, now set to: 1!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!

System information: Mac OS X 10.11.2 (15C50)
Brandstring 'Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz'

Checking Sandy Bridge processor data ...
Checking Ivy Bridge processor data ...
Checking Haswell processor data ...
Processor data found for the Intel E5-2680 v3
gModelDataVersion: 160 / gCPUDataVersion: 150
Downloading extractACPITables.zip ...Unzipping extractACPITables.zip ...Checking executing bit of extractACPITables ...Cleanups ...Extracting ACPI tables ... Done.
4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b82471f53434b30085f4849440d414350493030303400
5b82471f53434b31085f4849440d414350493030303400
5b82471f53434b32085f4849440d414350493030303400
5b82471f53434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK0) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
gProcessorStartIndex: 0
gLogicalCPUs        : 0
gProcessorNames     : 24
Searching for 24 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK1) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
gProcessorStartIndex: 0
gLogicalCPUs        : 0
gProcessorNames     : 24
Searching for 24 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK2) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK2) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
gProcessorStartIndex: 0
gLogicalCPUs        : 0
gProcessorNames     : 24
Searching for 24 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK3) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK3) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
gProcessorStartIndex: 0
gLogicalCPUs        : 0
gProcessorNames     : 24
Searching for 24 additional Processor declaration ...
Extracting ACPI tables ... Done.
Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core E5-2680 v3 processor [0x306F2] setup [0x0507]
Processor matched!
With a maximum TDP of 120 Watt, as specified by Intel
Number logical CPU's: 24 (Core Frequency: 2500 MHz)
Number of Turbo States: 8 (2600-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Downloading iasl.zip ...Unzipping iasl.zip ...Setting executing bit of iasl ...Cleanups ...Done.
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/lars/Library/ssdtPRGen/ssdt.dsl - 929 lines, 29308 bytes, 180 keywords
AML Output:    /Users/lars/Library/ssdtPRGen/ssdt.aml - 6039 bytes, 82 named objects, 98 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

---

HT was Disabled, when I ran "./ssdtPRGen.sh -cpus 2 -target 2 -d 3 -x 1 -w 1"..

Now I will enable HT and run the script again..

**Comment by analogo** [comment]
I tried "ssdtPRGen.sh -cpus 2 -target 2 -d 3 -x 1 -w 1" with all cores and HT enabled in BIOS (total amount of threads: 2 x 24).

By the way the CPUs are installed on a Supermicro X10DAi mainboard few day ago, which works better, but also is unresponsive/laggy and with audio playback full of crackling, because the music sequencers can use only one core. On Windows 8.1 and MacBook Pro the programs can use all cores..

Then I found out, that the ssdtPRGen.sh v17.0 script maybe collects the wrong cores..(?) Please look the following samples of the generated SSDT and DSDT..

SSDT:

 DefinitionBlock ("iASL3jHk2s.aml", "SSDT", 1, "APPLE ", "CpuPm", 0x00017000)
{
    External (_SB_.SCK3.CP17, DeviceObj)
    External (_SB_.SCK3.CP16, DeviceObj)
    External (_SB_.SCK3.CP15, DeviceObj)
    External (_SB_.SCK3.CP14, DeviceObj)
    External (_SB_.SCK3.CP13, DeviceObj)
    External (_SB_.SCK3.CP12, DeviceObj)
    External (_SB_.SCK2.CP11, DeviceObj)
    External (_SB_.SCK2.CP10, DeviceObj)
    External (_SB_.SCK2.CP0F, DeviceObj)
    External (_SB_.SCK2.CP0E, DeviceObj)
    External (_SB_.SCK2.CP0D, DeviceObj)
    External (_SB_.SCK2.CP0C, DeviceObj)
    External (_SB_.SCK1.CP0B, DeviceObj)
    External (_SB_.SCK1.CP0A, DeviceObj)
    External (_SB_.SCK1.CP09, DeviceObj)
    External (_SB_.SCK1.CP08, DeviceObj)
    External (_SB_.SCK1.CP07, DeviceObj)
    External (_SB_.SCK1.CP06, DeviceObj)
    External (_SB_.SCK0.CP05, DeviceObj)
    External (_SB_.SCK0.CP04, DeviceObj)
    External (_SB_.SCK0.CP03, DeviceObj)
    External (_SB_.SCK0.CP02, DeviceObj)
    External (_SB_.SCK0.CP01, DeviceObj)
    External (_SB_.SCK0.CP00, DeviceObj)

```
Scope (\_SB.SCK0.CP00)
{
    Method (_INI, 0, NotSerialized)
    {
        Store ("ssdtPRGen version....: 17.0 / Mac OS X 10.11.2 (15C50)", Debug)
        Store ("target processor.....: E5-2680 v3", Debug)
        Store ("source processor.....: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz", Debug)
        Store ("baseFrequency........: 1200", Debug)
        Store ("frequency............: 2500", Debug)
        Store ("busFrequency.........: 100", Debug)
        Store ("logicalCPUs..........: 24", Debug)
        Store ("maximum TDP..........: 120", Debug)
        Store ("packageLength........: 22", Debug)
        Store ("turboStates..........: 8", Debug)
        Store ("maxTurboFrequency....: 3300", Debug)
        Store ("IvyWorkArounds.......: 1", Debug)
        Store ("machdep.xcpm.mode....: 1", Debug)
        Store ("number of ACPI scopes: 4", Debug)
    }
```

---

DSDT:

```
        Device (SCK0)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK0")
            Processor (CP00, 0x00, 0x00000410, 0x06) {}
            Processor (CP01, 0x02, 0x00000410, 0x06) {}
            Processor (CP02, 0x04, 0x00000410, 0x06) {}
            Processor (CP03, 0x06, 0x00000410, 0x06) {}
            Processor (CP04, 0x08, 0x00000410, 0x06) {}
            Processor (CP05, 0x0A, 0x00000410, 0x06) {}
            Processor (CP06, 0x10, 0x00000410, 0x06) {}
            Processor (CP07, 0x12, 0x00000410, 0x06) {}
            Processor (CP08, 0x14, 0x00000410, 0x06) {}
            Processor (CP09, 0x16, 0x00000410, 0x06) {}
            Processor (CP0A, 0x18, 0x00000410, 0x06) {}
            Processor (CP0B, 0x1A, 0x00000410, 0x06) {}
            Processor (CP0C, 0x01, 0x00000410, 0x06) {}
            Processor (CP0D, 0x03, 0x00000410, 0x06) {}
            Processor (CP0E, 0x05, 0x00000410, 0x06) {}
            Processor (CP0F, 0x07, 0x00000410, 0x06) {}
            Processor (CP10, 0x09, 0x00000410, 0x06) {}
            Processor (CP11, 0x0B, 0x00000410, 0x06) {}
            Processor (CP12, 0x11, 0x00000410, 0x06) {}
            Processor (CP13, 0x13, 0x00000410, 0x06) {}
            Processor (CP14, 0x15, 0x00000410, 0x06) {}
            Processor (CP15, 0x17, 0x00000410, 0x06) {}
            Processor (CP16, 0x19, 0x00000410, 0x06) {}
            Processor (CP17, 0x1B, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }

        Device (SCK1)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK1")
            Processor (CP00, 0x20, 0x00000410, 0x06) {}
            Processor (CP01, 0x22, 0x00000410, 0x06) {}
            Processor (CP02, 0x24, 0x00000410, 0x06) {}
            Processor (CP03, 0x26, 0x00000410, 0x06) {}
            Processor (CP04, 0x28, 0x00000410, 0x06) {}
            Processor (CP05, 0x2A, 0x00000410, 0x06) {}
            Processor (CP06, 0x30, 0x00000410, 0x06) {}
            Processor (CP07, 0x32, 0x00000410, 0x06) {}
            Processor (CP08, 0x34, 0x00000410, 0x06) {}
            Processor (CP09, 0x36, 0x00000410, 0x06) {}
            Processor (CP0A, 0x38, 0x00000410, 0x06) {}
            Processor (CP0B, 0x3A, 0x00000410, 0x06) {}
            Processor (CP0C, 0x21, 0x00000410, 0x06) {}
            Processor (CP0D, 0x23, 0x00000410, 0x06) {}
            Processor (CP0E, 0x25, 0x00000410, 0x06) {}
            Processor (CP0F, 0x27, 0x00000410, 0x06) {}
            Processor (CP10, 0x29, 0x00000410, 0x06) {}
            Processor (CP11, 0x2B, 0x00000410, 0x06) {}
            Processor (CP12, 0x31, 0x00000410, 0x06) {}
            Processor (CP13, 0x33, 0x00000410, 0x06) {}
            Processor (CP14, 0x35, 0x00000410, 0x06) {}
            Processor (CP15, 0x37, 0x00000410, 0x06) {}
            Processor (CP16, 0x39, 0x00000410, 0x06) {}
            Processor (CP17, 0x3B, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }

        Device (SCK2)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK2")
            Processor (CP00, 0xFF, 0x00000410, 0x06) {}
            Processor (CP01, 0xFF, 0x00000410, 0x06) {}
            Processor (CP02, 0xFF, 0x00000410, 0x06) {}
            Processor (CP03, 0xFF, 0x00000410, 0x06) {}
            Processor (CP04, 0xFF, 0x00000410, 0x06) {}
            Processor (CP05, 0xFF, 0x00000410, 0x06) {}
            Processor (CP06, 0xFF, 0x00000410, 0x06) {}
            Processor (CP07, 0xFF, 0x00000410, 0x06) {}
            Processor (CP08, 0xFF, 0x00000410, 0x06) {}
            Processor (CP09, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP10, 0xFF, 0x00000410, 0x06) {}
            Processor (CP11, 0xFF, 0x00000410, 0x06) {}
            Processor (CP12, 0xFF, 0x00000410, 0x06) {}
            Processor (CP13, 0xFF, 0x00000410, 0x06) {}
            Processor (CP14, 0xFF, 0x00000410, 0x06) {}
            Processor (CP15, 0xFF, 0x00000410, 0x06) {}
            Processor (CP16, 0xFF, 0x00000410, 0x06) {}
            Processor (CP17, 0xFF, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }

        Device (SCK3)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK3")
            Processor (CP00, 0xFF, 0x00000410, 0x06) {}
            Processor (CP01, 0xFF, 0x00000410, 0x06) {}
            Processor (CP02, 0xFF, 0x00000410, 0x06) {}
            Processor (CP03, 0xFF, 0x00000410, 0x06) {}
            Processor (CP04, 0xFF, 0x00000410, 0x06) {}
            Processor (CP05, 0xFF, 0x00000410, 0x06) {}
            Processor (CP06, 0xFF, 0x00000410, 0x06) {}
            Processor (CP07, 0xFF, 0x00000410, 0x06) {}
            Processor (CP08, 0xFF, 0x00000410, 0x06) {}
            Processor (CP09, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP0F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP10, 0xFF, 0x00000410, 0x06) {}
            Processor (CP11, 0xFF, 0x00000410, 0x06) {}
            Processor (CP12, 0xFF, 0x00000410, 0x06) {}
            Processor (CP13, 0xFF, 0x00000410, 0x06) {}
            Processor (CP14, 0xFF, 0x00000410, 0x06) {}
            Processor (CP15, 0xFF, 0x00000410, 0x06) {}
            Processor (CP16, 0xFF, 0x00000410, 0x06) {}
            Processor (CP17, 0xFF, 0x00000410, 0x06) {}
            Processor (CP18, 0xFF, 0x00000410, 0x06) {}
            Processor (CP19, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1A, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1B, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1C, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1D, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1E, 0xFF, 0x00000410, 0x06) {}
            Processor (CP1F, 0xFF, 0x00000410, 0x06) {}
            Processor (CP20, 0xFF, 0x00000410, 0x06) {}
            Processor (CP21, 0xFF, 0x00000410, 0x06) {}
            Processor (CP22, 0xFF, 0x00000410, 0x06) {}
            Processor (CP23, 0xFF, 0x00000410, 0x06) {}
        }
    }
```

---

Maybe only this Processors should be used..(?):

```
        Device (SCK0)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK0")
            Processor (CP00, 0x00, 0x00000410, 0x06) {}
            Processor (CP01, 0x02, 0x00000410, 0x06) {}
            Processor (CP02, 0x04, 0x00000410, 0x06) {}
            Processor (CP03, 0x06, 0x00000410, 0x06) {}
            Processor (CP04, 0x08, 0x00000410, 0x06) {}
            Processor (CP05, 0x0A, 0x00000410, 0x06) {}
            Processor (CP06, 0x10, 0x00000410, 0x06) {}
            Processor (CP07, 0x12, 0x00000410, 0x06) {}
            Processor (CP08, 0x14, 0x00000410, 0x06) {}
            Processor (CP09, 0x16, 0x00000410, 0x06) {}
            Processor (CP0A, 0x18, 0x00000410, 0x06) {}
            Processor (CP0B, 0x1A, 0x00000410, 0x06) {}
            Processor (CP0C, 0x01, 0x00000410, 0x06) {}
            Processor (CP0D, 0x03, 0x00000410, 0x06) {}
            Processor (CP0E, 0x05, 0x00000410, 0x06) {}
            Processor (CP0F, 0x07, 0x00000410, 0x06) {}
            Processor (CP10, 0x09, 0x00000410, 0x06) {}
            Processor (CP11, 0x0B, 0x00000410, 0x06) {}
            Processor (CP12, 0x11, 0x00000410, 0x06) {}
            Processor (CP13, 0x13, 0x00000410, 0x06) {}
            Processor (CP14, 0x15, 0x00000410, 0x06) {}
            Processor (CP15, 0x17, 0x00000410, 0x06) {}
            Processor (CP16, 0x19, 0x00000410, 0x06) {}
            Processor (CP17, 0x1B, 0x00000410, 0x06) {}

        Device (SCK1)
        {
            Name (_HID, "ACPI0004")
            Name (_UID, "CPUSCK1")
            Processor (CP00, 0x20, 0x00000410, 0x06) {}
            Processor (CP01, 0x22, 0x00000410, 0x06) {}
            Processor (CP02, 0x24, 0x00000410, 0x06) {}
            Processor (CP03, 0x26, 0x00000410, 0x06) {}
            Processor (CP04, 0x28, 0x00000410, 0x06) {}
            Processor (CP05, 0x2A, 0x00000410, 0x06) {}
            Processor (CP06, 0x30, 0x00000410, 0x06) {}
            Processor (CP07, 0x32, 0x00000410, 0x06) {}
            Processor (CP08, 0x34, 0x00000410, 0x06) {}
            Processor (CP09, 0x36, 0x00000410, 0x06) {}
            Processor (CP0A, 0x38, 0x00000410, 0x06) {}
            Processor (CP0B, 0x3A, 0x00000410, 0x06) {}
            Processor (CP0C, 0x21, 0x00000410, 0x06) {}
            Processor (CP0D, 0x23, 0x00000410, 0x06) {}
            Processor (CP0E, 0x25, 0x00000410, 0x06) {}
            Processor (CP0F, 0x27, 0x00000410, 0x06) {}
            Processor (CP10, 0x29, 0x00000410, 0x06) {}
            Processor (CP11, 0x2B, 0x00000410, 0x06) {}
            Processor (CP12, 0x31, 0x00000410, 0x06) {}
            Processor (CP13, 0x33, 0x00000410, 0x06) {}
            Processor (CP14, 0x35, 0x00000410, 0x06) {}
            Processor (CP15, 0x37, 0x00000410, 0x06) {}
            Processor (CP16, 0x39, 0x00000410, 0x06) {}
            Processor (CP17, 0x3B, 0x00000410, 0x06) {}
```

---

Not have much time to test, because I´m in 12 hours (17:00 PM / GMT +1) for about four weeks away from home..

It would be great, if you could give me something to test before I´m away from home, because after incessantly trying to get a perfect working machine over months, I need a lift and that it is possible to get the machine working smoothly without crackling audio playback with RME HDSPe AIO (PCIe) or RME Babyface (USB2) audio interfaces..

Many many Thanks! :)

**Comment by Piker-Alpha** [comment]
The following terminal commands produce the correct SSDT (with the DSDT you e-mailed me): 

./ssdtPRGenCopy.sh -p 'E5-2680 v3' -cpus 2 -target 2 -l 24 -x 1 -w 1
./ssdtPRGenCopy.sh -p 'E5-2680 v3' -cpus 2 -target 2 -l 36 -x 1 -w 1

So what is the problem with the -l argument?

Note: I added the -p argument otherwise it would use my CPU specs.

What do you get when you run:

<code>ioreg -p IODeviceTree -c IOACPIPlatformDevice -k cpu-type -k clock-frequency | egrep name  | sed -e 's/ *[-|="<a-z>]//g'</code>

You are not editing the script in any way, are you?

Also. If you lower the logical core count, by disabling hyper-threading or whatever, then also change the CPU data for your processors. Otherwise the script collects the wrong data.

**Comment by analogo** [comment]
Thank you, I will try it and give you shortly a feedback.. :)

Have you read my previous posting?

Edit:
Do I have to use the -l parameter, if all cores and HT are enabled in BIOS?

**Comment by Piker-Alpha** [comment]
With one CPU not, but with two or more then you should use the -l argument. And if you are running a different CPU, like me with 8 logical cores, then also yes.

**Comment by analogo** [comment]
Ahhh, ok, thank you.. Didn´t try that.. I will be awake and give you shortly a feedback.. :)

Edit:
Will try with -l 48 and without the -p parameter..

**Comment by Piker-Alpha** [comment]
Don't forget the ioreg output.

**Comment by analogo** [comment]
Ok.. Now I have read your editet post.. First I will test that and give you all the informations..

**Comment by Piker-Alpha** [comment]
BTW: I did not edit the CPU data so using -l also takes care of the logical core count.

**Comment by analogo** [comment]
Ok, I will use -l 48..

By the way I didn´t edit anything of your v17.0 files, which are included in the downloaded ZIP file..

**Comment by Piker-Alpha** [comment]
Without -l 24 I am getting:

```
External (\_SB_.SCK0.CP00, DeviceObj)
External (\_SB_.SCK0.CP01, DeviceObj)
External (\_SB_.SCK0.CP02, DeviceObj)
External (\_SB_.SCK0.CP03, DeviceObj)
External (\_SB_.SCK0.CP04, DeviceObj)
External (\_SB_.SCK0.CP05, DeviceObj)
External (\_SB_.SCK1.CP06, DeviceObj)
External (\_SB_.SCK1.CP07, DeviceObj)
External (\_SB_.SCK1.CP08, DeviceObj)
External (\_SB_.SCK1.CP09, DeviceObj)
External (\_SB_.SCK1.CP0A, DeviceObj)
External (\_SB_.SCK1.CP0B, DeviceObj)
External (\_SB_.SCK2.CP00, DeviceObj)
External (\_SB_.SCK2.CP01, DeviceObj)
External (\_SB_.SCK2.CP02, DeviceObj)
External (\_SB_.SCK2.CP03, DeviceObj)
External (\_SB_.SCK2.CP04, DeviceObj)
External (\_SB_.SCK2.CP05, DeviceObj)
External (\_SB_.SCK3.CP06, DeviceObj)
External (\_SB_.SCK3.CP07, DeviceObj)
External (\_SB_.SCK3.CP08, DeviceObj)
External (\_SB_.SCK3.CP09, DeviceObj)
External (\_SB_.SCK3.CP0A, DeviceObj)
External (\_SB_.SCK3.CP0B, DeviceObj)
```

With -l 24 I am getting:

```
External (\_SB_.SCK0.CP00, DeviceObj)
External (\_SB_.SCK0.CP01, DeviceObj)
External (\_SB_.SCK0.CP02, DeviceObj)
External (\_SB_.SCK0.CP03, DeviceObj)
External (\_SB_.SCK0.CP04, DeviceObj)
External (\_SB_.SCK0.CP05, DeviceObj)
External (\_SB_.SCK0.CP06, DeviceObj)
External (\_SB_.SCK0.CP07, DeviceObj)
External (\_SB_.SCK0.CP08, DeviceObj)
External (\_SB_.SCK0.CP09, DeviceObj)
External (\_SB_.SCK0.CP0A, DeviceObj)
External (\_SB_.SCK0.CP0B, DeviceObj)
External (\_SB_.SCK1.CP00, DeviceObj)
External (\_SB_.SCK1.CP01, DeviceObj)
External (\_SB_.SCK1.CP02, DeviceObj)
External (\_SB_.SCK1.CP03, DeviceObj)
External (\_SB_.SCK1.CP04, DeviceObj)
External (\_SB_.SCK1.CP05, DeviceObj)
External (\_SB_.SCK1.CP06, DeviceObj)
External (\_SB_.SCK1.CP07, DeviceObj)
External (\_SB_.SCK1.CP08, DeviceObj)
External (\_SB_.SCK1.CP09, DeviceObj)
External (\_SB_.SCK1.CP0A, DeviceObj)
External (\_SB_.SCK1.CP0B, DeviceObj)
```

**Comment by analogo** [comment]
Great.. I´m curios.. :)

By the way, with freqVectorsEdit script I used iMac15,1 instead of MacBookPro11,3.. Was that ok?

Edit:
With that parameters I got a fourth SSDT file (SSDT-3.aml).. The files and informations follows shortly..

**Comment by Piker-Alpha** [comment]
Need to help out with breakfast for our guests. Please add the output of the ioreg command.

**Comment by analogo** [comment]
So.. the system again is laggy like hell.. :(

Here is the output and the rest follows..

ioreg -p IODeviceTree -c IOACPIPlatformDevice -k cpu-type -k clock-frequency | egrep name | sed -e 's/ *[-|="]//g'

name CP00>
name CP01>
name CP02>
name CP03>
name CP04>
name CP05>
name CP06>
name CP07>
name CP08>
name CP09>
name CP0A>
name CP0B>
name CP0C>
name CP0D>
name CP0E>
name CP0F>
name CP10>
name CP11>
name CP12>
name CP13>
name CP14>
name CP15>
name CP16>
name CP17>
name CP00>
name CP01>
name CP02>
name CP03>
name CP04>
name CP05>
name CP06>
name CP07>
name CP08>
name CP09>
name CP0A>
name CP0B>
name CP0C>
name CP0D>
name CP0E>
name CP0F>
name CP10>
name CP11>
name CP12>
name CP13>
name CP14>
name CP15>
name CP16>
name CP17>

Had to delete the "<"..

Enjoy your meal! :) I´m hungry too.. :D

**Comment by analogo** [comment]
Think your script did it..(?)

With ./ssdtPRGen.sh -cpus 2 -target 2 -d 3 -l 48 -x 1 -w 1 ...

ssdtPRGen.sh v0.9 Copyright (c) 2011-2012 by † RevoGirl
             v6.6 Copyright (c) 2013 by † Jeroen

##              v17.0 Copyright (c) 2013-2016 by Pike R. Alpha

Bugs > https://github.com/Piker-Alpha/ssdtPRGen.sh/issues <

Override value: (-cpus) number of processors, now using: 2!
Override value: (-target) CPU, now using: Haswell!
Override value: (-d) debug mode, now using: 3!
Override value: (-l) number of logical cores, now using: 48!
Override value: (-x) XCPM mode, now set to: 1!
Override value: (-w) Ivy Bridge workarounds, now set to: 1!

System information: Mac OS X 10.11.2 (15C50)
Brandstring 'Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz'

Checking Sandy Bridge processor data ...
Checking Ivy Bridge processor data ...
Checking Haswell processor data ...
Processor data found for the Intel E5-2680 v3
gModelDataVersion: 160 / gCPUDataVersion: 150
Downloading extractACPITables.zip ...Unzipping extractACPITables.zip ...Checking executing bit of extractACPITables ...Cleanups ...Extracting ACPI tables ... Done.
4 Name (_HID, "ACPI0004") object(s) found in the DSDT
matchingData:
5b82471f53434b30085f4849440d414350493030303400
5b82471f53434b31085f4849440d414350493030303400
5b82471f53434b32085f4849440d414350493030303400
5b82471f53434b33085f4849440d414350493030303400
Searching for ACPI Processor declarations in Device(SCK0) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK0) (non ACPI 1.0 compliant)
logicalCore: 0 CP00
logicalCore: 1 CP01
logicalCore: 2 CP02
logicalCore: 3 CP03
logicalCore: 4 CP04
logicalCore: 5 CP05
logicalCore: 6 CP06
logicalCore: 7 CP07
logicalCore: 8 CP08
logicalCore: 9 CP09
logicalCore: 10 CP0A
logicalCore: 11 CP0B
logicalCore: 12 CP0C
logicalCore: 13 CP0D
logicalCore: 14 CP0E
logicalCore: 15 CP0F
logicalCore: 16 CP10
logicalCore: 17 CP11
logicalCore: 18 CP12
logicalCore: 19 CP13
logicalCore: 20 CP14
logicalCore: 21 CP15
logicalCore: 22 CP16
logicalCore: 23 CP17
logicalCore: 24 CP00
gProcessorStartIndex: 24
gLogicalCPUs        : 48
gProcessorNames     : 48
Searching for 24 additional Processor declaration ...
Searching for ACPI Processor declarations in Device(SCK1) {}
Two-byte encoding detected (maximum length 0x0FFF/4095)
pkgLengthByte: 0x47/71
packageLength: 0x1f7/503
scopeLength: 503
ACPI Processor declaration (CP00) {0x0b bytes} found in Device (SCK1) (non ACPI 1.0 compliant)
logicalCore: 24 CP00
logicalCore: 25 CP01
logicalCore: 26 CP02
logicalCore: 27 CP03
logicalCore: 28 CP04
logicalCore: 29 CP05
logicalCore: 30 CP06
logicalCore: 31 CP07
logicalCore: 32 CP08
logicalCore: 33 CP09
logicalCore: 34 CP0A
logicalCore: 35 CP0B
logicalCore: 36 CP0C
logicalCore: 37 CP0D
logicalCore: 38 CP0E
logicalCore: 39 CP0F
logicalCore: 40 CP10
logicalCore: 41 CP11
logicalCore: 42 CP12
logicalCore: 43 CP13
logicalCore: 44 CP14
logicalCore: 45 CP15
logicalCore: 46 CP16
logicalCore: 47 CP17
Extracting ACPI tables ... Done.
Generating ssdt.dsl for a 'MacPro6,1' with board-id [Mac-F60DEB81FF30ACF6]
Haswell Core E5-2680 v3 processor [0x306F2] setup [0x0507]
Processor matched!
With a maximum TDP of 120 Watt, as specified by Intel
Number logical CPU's: 48 (Core Frequency: 2500 MHz)
Number of Turbo States: 8 (2600-3300 MHz)
Number of P-States: 22 (1200-3300 MHz)
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
targetCStates: 13
Adding C1
Adding C3
Adding C6
Injected C-States for CP00 (C1,C3,C6)
Injected C-States for CP01 (C1,C3,C6)
Downloading iasl.zip ...Unzipping iasl.zip ...Setting executing bit of iasl ...Cleanups ...Done.
Intel ACPI Component Architecture
ASL Optimizing Compiler version 20140926-64 [Nov  6 2014]
Copyright (c) 2000 - 2014 Intel Corporation

ASL Input:     /Users/lars/Library/ssdtPRGen/ssdt.dsl - 961 lines, 26980 bytes, 316 keywords
AML Output:    /Users/lars/Library/ssdtPRGen/ssdt.aml - 7305 bytes, 150 named objects, 166 executable opcodes

Compilation complete. 0 Errors, 0 Warnings, 0 Remarks, 0 Optimizations

**Comment by analogo** [comment]
Here are all the files:
[System 2015-01-13.zip](https://github.com/Piker-Alpha/ssdtPRGen.sh/files/88388/System.2015-01-13.zip)

Can you also look the files please, why my system is so extremely sluggish and the audio playback is full of crackling?

If my system finally works smoothly, then I will write a guide on insanelymac for example. The complete Hackintosh community would benefit if we can finally take advantage of OS X in conjunction with a lot of processor power.

I would also like to donate you, if you like, for your fantastic work!

Many Thanks! :)

**Comment by analogo** [comment]
Also have eMailed you the ZIP file a few minutes ago..

Please let me know before I´m away from home for about four weeks, if you need more details or files..

**Comment by Piker-Alpha** [comment]
The new script output with -l 48 is looking fine, but I don't have time to look at your files right now. Maybe tonight, when I fixed a couple other related bugs. After that it should run without the -l argument.

**Comment by analogo** [comment]
Ok, many Thanks Pike! :)

**Comment by bt** [comment]
Would be looking forward to solving this laggy issue too!

I've done a lot of research and it seems it has to do with multiple CPUs not working well with the Nvidia Web Drivers.

I hope it's not an issue with their drivers; otherwise we'd have to wait ages for them to fix such an edge case :cry:

**Comment by Piker-Alpha** [comment]
@analogo,

Update: ssdtPRGen.sh v17.2 should now only need -cpus 2

@bt,

So there is no lag with one processor installed/enabled in the BIOS??

**Comment by bt** [comment]
Hey Pike,

Well, what I've read and noticed is the following:
- people having unresponsive/lag issues all have dual CPUs installed with the Nvidia Web Drivers enabled (nvda_drv=1)
- I can't confirm that disabling the 2nd CPU via BIOS can solve the problem because my stupid motherboard doesn't have the ability to disable a single CPU.
- using flag 'cpus=1' doesn't solve the problem
- I read that the only solution at the moment is physically removing the 2nd processor from the motherboard but I can't confirm this because my machine KPs without the 2nd processor installed for some reason

I was able to run my machine flawlessly without the Nvidia Web Drivers (ie. using an older graphics card + Clover Nvidia injection) but for some reason, injection stopped working once I upgraded from Yosemite to El Capitan so now I'm stuck with trying to fix this issue.

**Comment by Piker-Alpha** [comment]
Ok so this issue may actually be unrelated to the script, and impossible to fix without the help of Nvidia. Good to know. Thanks!
